-- 006 Parse Job Registry — additive migration
-- Spec: specs/006-parse-job-registry

CREATE TABLE IF NOT EXISTS kb_parse_run (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  run_uid VARCHAR(64) NOT NULL UNIQUE COMMENT 'parse_run_{UTC}_{short_uuid}',
  parser_name VARCHAR(64) NOT NULL COMMENT '005: markitdown',
  parser_adapter_version VARCHAR(128) NOT NULL COMMENT '005: 005_mvp_v1',
  parser_family VARCHAR(64) NOT NULL DEFAULT 'MARKITDOWN_FAMILY',
  trigger_type VARCHAR(64) NOT NULL DEFAULT 'REGISTER_REPORT' COMMENT 'REGISTER_REPORT | RECONCILE',
  filters_json JSON COMMENT '来自 report.filters 或 CLI filter',
  status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  dry_run TINYINT(1) NOT NULL DEFAULT 0 COMMENT '持久化 run 恒为 0',
  total_candidates INT NOT NULL DEFAULT 0,
  in_scope_candidates INT NOT NULL DEFAULT 0,
  parsed_count INT NOT NULL DEFAULT 0,
  skipped_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  empty_count INT NOT NULL DEFAULT 0,
  report_path TEXT COMMENT '源 parse_markitdown_report 路径',
  registry_report_path TEXT COMMENT '006 输出的 registry_report 路径',
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  error_message TEXT,
  metadata JSON,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_parse_run_report (report_path(512), parser_adapter_version),
  KEY idx_parser_name (parser_name),
  KEY idx_status (status),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Batch parse run registry (006 parse job)';

CREATE TABLE IF NOT EXISTS kb_parse_result (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  result_uid VARCHAR(64) NOT NULL UNIQUE,
  run_uid VARCHAR(64) NOT NULL,
  content_uid VARCHAR(64) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  route_type VARCHAR(64),
  decision VARCHAR(64),
  status VARCHAR(64) NOT NULL,
  source_vault_path TEXT,
  parsed_dir TEXT,
  manifest_path TEXT,
  metadata_path TEXT,
  text_path TEXT,
  output_hash CHAR(64),
  output_size_bytes BIGINT,
  error_code VARCHAR(128),
  error_message TEXT,
  retry_of_result_id BIGINT NULL COMMENT '指向前一次失败 result.id',
  parser_name VARCHAR(64) NOT NULL,
  parser_adapter_version VARCHAR(128) NOT NULL,
  pipeline_version VARCHAR(64) NOT NULL DEFAULT 'v1.1',
  metadata JSON,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_parse_result_run_content (run_uid, content_uid, parser_adapter_version),
  KEY idx_run_uid (run_uid),
  KEY idx_content_uid (content_uid),
  KEY idx_sha256 (sha256),
  KEY idx_status (status),
  KEY idx_retry_of (retry_of_result_id),
  CONSTRAINT fk_parse_result_run FOREIGN KEY (run_uid) REFERENCES kb_parse_run(run_uid),
  CONSTRAINT fk_parse_result_retry FOREIGN KEY (retry_of_result_id) REFERENCES kb_parse_result(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Per-content parse result within a run';

CREATE TABLE IF NOT EXISTS kb_parsed_artifact (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  artifact_uid VARCHAR(64) NOT NULL UNIQUE,
  run_uid VARCHAR(64) NOT NULL,
  content_uid VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'run 级 PARSE_REPORT 用空字符串 sentinel',
  sha256 CHAR(64) NULL,
  artifact_type VARCHAR(64) NOT NULL,
  artifact_path TEXT NOT NULL,
  artifact_hash CHAR(64),
  artifact_size_bytes BIGINT,
  parser_name VARCHAR(64) NOT NULL,
  parser_adapter_version VARCHAR(128) NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'INDEXED',
  metadata JSON,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_artifact_scope (run_uid, content_uid, artifact_type, parser_name, parser_adapter_version),
  KEY idx_run_uid (run_uid),
  KEY idx_sha256 (sha256),
  KEY idx_artifact_type (artifact_type),
  CONSTRAINT fk_parsed_artifact_run FOREIGN KEY (run_uid) REFERENCES kb_parse_run(run_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Parsed disk artifact index';
